### ISSUE TITLE
win11更新到22000.675后, 热替换功能失效

### ISSUE THREAD

**Issue by letterk** [snowie2000/mactype#859]
11号更新了5个更新
>2022-适用于 Windows 11 的 05 累积更新，适合基于 x64 的系统 (KB5013943)
>2022-05 用于 .NET Framework 3.5 和 4.8 的累积更新，适合基于 x64 的 Windows 11 (KB5013628)
>2022-05 .NET 5.0.17 Security Update for x64 Client (KB5014329)
>2022-05 .NET 6.0.5 Security Update for x64 Client (KB5014330)
>2022-05 .NET Core 3.1.25 Security Update for x64 Client (KB5014326)

重启后打开浏览器就发现, 要么替换成了□□, 要么就是无法替换
![Snipaste_2022-05-11_09-45-49](https://user-images.githubusercontent.com/9822709/167752697-4d1b7899-b79f-45aa-8e1a-f2c42f69ce73.png)
看着这屎一样的simsum ~~(死妈送)~~

奇怪的是试着卸载了`KB5013943`和`KB5013628`, 并不能恢复原来正常工作的样子. 另外三个是安全更新, 不提供卸载. 所以目前无法完全确定是更新导致的. 但我**昨晚更新关机, 今早开机就不正常了**

**Comment by letterk** [comment]
我的相关配置
>;===== 标识为Browser的通用配置组 =====
[General@Browser]
;【针对Browser组的字体替换】
FontSubstitutes=1
[FontSubstitutes@Browser]
;针对Browser组的字体替换，当FontSubstitutes>0时生效
Courier New=DejaVuSansMono NF
Arial=Source Han Sans SC                   ;`方块字`
SimSun=Source Han Sans SC               ;`失效`
NSimSun=Source Han Sans SC
Microsoft YaHei=Source Han Sans SC
>[General@chrome.exe]
Alternative=Browser
[General@firefox.exe]
Alternative=Browser

**Comment by snowie2000** [comment]
directwrite的替换依赖于dw本身的实现，Windows随时会修改dw的实现，故无法保证效果和跨版本的兼容性。

**Comment by letterk** [comment]
唉, 那只能用css做替换了. 由于各个网站的在写样式表时, 普遍才用"水面大法"不考虑继承关系, 一律层层覆盖. 很难写出全网通用的css规则. 不如mactype直接针对字体热替换省事.

**Comment by tcbbd** [comment]
Win10遇到了同样的问题，DirectWrite下无法替换字体，怀疑是安全补丁KB5013942更新引起的，但卸载后并没解决问题

**Comment by tcbbd** [comment]
> 唉, 那只能用css做替换了. 由于各个网站的在写样式表时, 普遍才用"水面大法"不考虑继承关系, 一律层层覆盖. 很难写出全网通用的css规则. 不如mactype直接针对字体热替换省事.

可以用font-face替换，但Chrome和Firefox引用的字体名不同：

Chrome:
```css
@font-face {
    font-family: "Microsoft YaHei UI";
    src: local("PingFang SC Regular");
}

@font-face {
    font-family: "Microsoft YaHei";
    src: local("PingFang SC Regular");
}

@font-face {
    font-family: "微软雅黑";
    src: local("PingFang SC Regular");
}
```
Firefox:
```css
@font-face {
    font-family: "Microsoft YaHei UI";
    src: local("PingFang SC");
}

@font-face {
    font-family: "Microsoft YaHei";
    src: local("PingFang SC");
}

@font-face {
    font-family: "微软雅黑";
    src: local("PingFang SC");
}
```

Firefox用的就是字体的名字，Chrome好像还加上了字重什么的，有时直接加个Regular没用，导致我想选个字体但不知道名字选不了，非常坑爹。
